# Generated by Django 4.2.3 on 2023-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_estreno', models.DateField()),
                ('director', models.CharField(max_length=40)),
                ('elenco', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_estreno', models.DateField()),
                ('taquilla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('director', models.CharField(max_length=40)),
                ('elenco', models.CharField(max_length=200)),
                ('duracion', models.DurationField()),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_emision', models.DateField()),
                ('director', models.CharField(max_length=40)),
                ('elenco', models.CharField(max_length=200)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_estreno', models.DateField()),
                ('director', models.CharField(max_length=40)),
                ('elenco', models.CharField(max_length=200)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
