# Generated by Django 4.2.3 on 2023-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_entrega_final', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='director',
            new_name='productor',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='taquilla',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
