# Generated by Django 4.2.3 on 2023-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_entrega_final', '0002_rename_director_series_productor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentales',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
