# Generated by Django 4.2.3 on 2023-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_entrega_final', '0003_documentales_duracion_alter_peliculas_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentales',
            name='genero',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='genero',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
