# Generated by Django 4.2.3 on 2023-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_entrega_final', '0006_peliculas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenespeliculas/'),
        ),
    ]
