# Generated by Django 4.2.3 on 2023-08-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_entrega_final', '0008_alter_peliculas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenespeliculas'),
        ),
        migrations.AddField(
            model_name='programas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenespeliculas'),
        ),
        migrations.AddField(
            model_name='series',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenespeliculas'),
        ),
    ]
